export var op = [
  {
    imgs: [
      require("../data/op-1-1.jpg"),
      require("../data/op-1-2.jpg"),
      require("../data/op-1-3.jpg"),
      require("../data/op-1-4.jpg"),
    ],
    name: "Salma Abdelhamid",
    age: 19,
    case: "Class I Lower left 6",
    treatment: "Composite restoration under rubber dam isolation",
    extraNotes: "This was my first operative case",
  },
  {
    imgs: [
      require("../data/op-2-1.jpg"),
      require("../data/op-2-2.jpg"),
      require("../data/op-2-3.jpg"),
      require("../data/op-2-4.jpg"),
      require("../data/op-2-5.jpg"),
    ],
    name: "Anas Mamdouh",
    age: 18,
    case: "Class I Lower left 6 & 7",
    treatment: "GI restoration [Fuji IX (A3 shade)]",
    extraNotes:
      "After excavation of soft caries the cavity depth of lower 7 was 5mm!",
  },
  {
    imgs: [
      require("../data/op-3-1.jpg"),
      require("../data/op-3-2.jpg"),
      require("../data/op-3-3.jpg"),
      require("../data/op-3-4.jpg"),
      require("../data/op-3-5.jpg"),
      require("../data/op-3-6.jpg"),
      require("../data/op-3-7.jpg"),
    ],
    name: "Tadros Rayan",
    age: 31,
    case: "Class III Upper Right 1 & 2",
    treatment: "GI restoration [Riva resin modified (A2 shade)]",
    extraNotes:
      "A prominent pulp shadow on upper lateral was seen mesially and distally",
  },
  {
    imgs: [
      require("../data/op-4-1.jpg"),
      require("../data/op-4-2.jpg"),
      require("../data/op-4-3.jpg"),
    ],
    name: "Abd-Elrahman Abd-Elhamid",
    age: 28,
    case: "Class V Upper Right 3 & 4",
    treatment: "GI restoration [Riva resin modified (A2 shade)]",
    extraNotes: "Cotton roll isolation was used",
  },
  {
    imgs: [
      require("../data/op-5-1.jpg"),
      require("../data/op-5-2.jpg"),
      require("../data/op-5-3.jpg"),
      require("../data/op-5-4.jpg"),
      require("../data/op-5-5.jpg"),
      require("../data/op-5-6.jpg"),
      require("../data/op-5-7.jpg"),
    ],
    name: "Yehia Hamdy",
    age: 64,
    case: "Class II Upper Right 5",
    treatment: "Composite restoration",
    extraNotes: "Cotton roll isolation was used",
  },
  {
    imgs: [
      require("../data/op-6-1.jpg"),
      require("../data/op-6-2.jpg"),
      require("../data/op-6-3.jpg"),
      require("../data/op-6-4.jpg"),
      require("../data/op-6-5.jpg"),
      require("../data/op-6-6.jpg"),
      require("../data/op-6-7.jpg"),
    ],
    name: "Eman Ahmed",
    age: 44,
    case: "Class II Upper Right 5",
    treatment: "Composite restoration",
    extraNotes: "Cotton roll isolation was used",
  },
  {
    imgs: [
      require("../data/op-7-1.jpg"),
      require("../data/op-7-2.jpg"),
      require("../data/op-7-3.jpg"),
      require("../data/op-7-4.jpg"),
      require("../data/op-7-5.jpg"),
      require("../data/op-7-6.jpg"),
      require("../data/op-7-7.jpg"),
      require("../data/op-7-8.jpg"),
      require("../data/op-7-9.jpg"),
    ],
    name: "Amany Mohamed",
    age: 47,
    case: "Class II Upper Right 5",
    treatment: "Composite restoration under Cotton roll isolation",
    extraNotes: "This was a very deep cavity but with no S&S",
  },
];
